#!/bin/sh

if [ $# -ne 2 ]; then
    echo Usage: $0 CGI-BIN DOCUMENT-ROOT
    exit 1
fi

CGI_BIN="$1"
DOCUMENT_ROOT=$(realpath $2)

# Copy program files into CGI bin directory
cp -r cgi-bin/* "$CGI_BIN"
chmod +x "$CGI_BIN"/wiklet.pl
sed -i "s|\"/home/user/public_html\"|\"$DOCUMENT_ROOT\"|" "$CGI_BIN"/wiklet.pl

# Copy data files to document root
cp -a text template "$DOCUMENT_ROOT"
mkdir "$DOCUMENT_ROOT"/download "$DOCUMENT_ROOT"/image
chmod -R +w "$DOCUMENT_ROOT"/text/*

# Create a new git repository
cd "$DOCUMENT_ROOT"/text
git init .
git add *
git commit -m "Initial commit"

echo
echo "Now see the installation instructions or '$CGI_BIN/wiklet.pl' for further setup"
