#! /bin/sh
# wikletpage
# Make a Wiklet page for an included document
# R.R.T.   3/9, 17, 23/11/02, 23/2/03, 16/3/04

name=`basename $0`

if [ $# -eq 2 ]; then
    page=~/public_html/text/$1
    file=$2
    if [ -e "$page" ]; then
        echo "$page already exists"
        exit 1
    fi
    echo "\$include{$file.html}" >> $page
else
    echo "Usage: $name PAGE FILE (.html added automatically)"
    exit 1
fi
