#! /usr/bin/perl -w
# Convert a plain text Data::Dumper pickle to a network-order Storable file
# RRT 28/2/03

use strict;
use warnings;

use Storable;
use lib "/home/rrt/public_html/cgi-bin";
use RRT::Misc;

foreach my $file(@ARGV) {
  my $obj = eval readFile($file);
  nstore $obj, $file;
}
