#! /usr/bin/perl -w
# Convert a plain text file to an RRT::RevHistory pickle
# RRT 2-3/03, 8/10/03

require 5.003;

use strict;
use warnings;

use Storable qw(retrieve nstore);
use lib "/home/rrt/public_html/cgi-bin";
use RRT::Misc;
use RRT::RevHistory;

foreach my $file(@ARGV) {
  my $text = readFile($file);
  my $hist = RRT::RevHistory->new($text);
  nstore $hist, $file;
}
